coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: reach, diff, files
  behavior: default
  require_base: yes
  require_head: yes
  after_n_builds: 5 # Our test matrix currently has 5 configurations
