[files]
extend-exclude = ["src/core_editor/line_buffer.rs"]

[default.extend-words]
# Ignore false-positives
iterm = "iterm"
# For testing completion of the word build
bui = "bui"
# For testing string truncation
descriptio = "descriptio"
ot = "ot"
# for sqlite backed history
wheres = "wheres"
