[package]
name = "reedline"
version = "0.1.0"
authors = ["Jonathan Turner <jonathan.d.turner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
unicode-segmentation = "1.7.1"
chrono = "0.4.19"
unicode-width = "0.1.8"