[package]
name = "reedline"
version = "0.1.0"
authors = ["Jonathan Turner <jonathan.d.turner@gmail.com>"]
edition = "2018"
description = "A readline-like crate for CLI text input"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = true

[[bin]]
name = "reedline"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
clipboard = { version = "0.5.0", optional = true }
crossterm = { version = "0.21.0", features = ["serde"] }
nu-ansi-term = "0.36.0"
serde = { version = "1.0", features = ["derive"] }
unicode-segmentation = "1.7.1"
unicode-width = "0.1.8"

[dev-dependencies]
tempfile = "3.2.0"
pretty_assertions = "0.7.2"
rstest = "0.11.0"

[features]
system_clipboard = ["clipboard"]
